### PR TITLE
HTM-804 Support XML Capabilities audio_system pass through status

### PR DESCRIPTION
**Pull request by danips**
audio_system pass_through attribute has been added in HbbTV 2.0.4

### CODE REVIEW

**Comment by LiyunOBS** [comment]
I happened to look into the same implementation, but found your pull-request.
This is probably related to passthrough status in orb-public/rdk/ORB/library/src/core/utilities/JsonUtil.cpp as well?
```
json JsonUtil::CapabilitiesToJsonObject(std::shared_ptr<Capabilities> capabilities)
{
    ....
    if (!capabilities->m_audioOutputFormat.empty())
    {
        jsonCapabilities.emplace("audioOutputFormat", capabilities->m_audioOutputFormat);
    }
```

**Comment by danips** [comment]
I have added the fixes from https://github.com/OpenRedButtonProject/orb/pull/308 in this pull request to avoid conflicts.
This is the description of the other pull request:

- display_size width and height are xs:integer, not xs:decimal.
- video_display_format, display_size, audio_system, html5_media_variable_rate, and json_rpc_server are children of profilelist/ui_profile/ext, not profilelist.

Check hbbtv_termcap_h204_example.xml example from TS 102 796 1.7.1 https://portal.etsi.org/webapp/workprogram/Report_WorkItem.asp?WKI_ID=68486

TS 102 796 1.7.1 Electronic attachments in here:
https://www.etsi.org/deliver/etsi_ts/102700_102799/102796/01.07.01_60/ts_102796v010701p0.zip

**Comment by joshua-h** [comment]
Can you please rebase @danips

**Comment by joshua-h** [comment]
Merge attempt failed

We couldn’t merge this pull request. Reload the page before trying again.

**Pull request merged**
